<?php
/**
 * =============================================================================
 *  datos_curiosos.php  —  UN DATO CURIOSO POR CADA ELEMENTO
 * =============================================================================
 *
 *  Es el diccionario  DatosCuriosos  que en Python estaba escrito DENTRO de la
 *  función Datos() del archivo datos.py.
 *
 *  Sacarlo de adentro de la función y ponerlo en su propio archivo es una buena
 *  práctica: los DATOS por un lado y la LÓGICA (el código que los usa) por otro.
 *  Así, si mañana querés corregir un dato curioso, sabés exactamente dónde
 *  buscar y no tenés que tocar nada del programa.
 *
 *  Ojo con "oganeson": en el original su texto está vacío porque se genera solo,
 *  calculando cuál es el elemento de mayor masa atómica. Eso se sigue haciendo
 *  en curiosos.php, igual que en el Python.
 * =============================================================================
 */

$datosCuriosos = [
    'hidrogeno'    => 'Es el elemento más abundante del universo (≈74% de la materia baryónica). Las estrellas mueren cuando se les acaba el hidrógeno para fusionar.',
    'helio'        => 'Fue descubierto primero en el Sol (1868) antes que en la Tierra. Hace la voz aguda porque el sonido viaja más rápido en él.',
    'litio'        => 'El metal más ligero (flota incluso en aceite). Las baterías de litio arden violentamente con agua.',
    'berilio'      => 'Transparente a los rayos X (ventanas de tubos de rayos X). Extremadamente tóxico al inhalarlo.',
    'boro'         => 'El bórax se usaba para momificar en el Antiguo Egipto. El boro puro es casi tan duro como el diamante.',
    'carbono'      => 'Forma más de 10 millones de compuestos conocidos. El grafeno es 200 veces más resistente que el acero.',
    'nitrogeno'    => '78% del aire que respiras, pero tu cuerpo no lo usa. La nitroglicerina explota con un golpe leve.',
    'oxigeno'      => 'El oxígeno puro es tóxico si se respira mucho tiempo. El ozono (O₃) es el olor típico después de una tormenta.',
    'fluor'        => 'El elemento más reactivo y electronegativo. El ácido fluorhídrico disuelve el vidrio.',
    'neon'         => 'Los carteles “de neón” rojos son realmente de neón; otros colores usan otros gases nobles.',
    'sodio'        => 'Explota en contacto con agua y se corta como mantequilla. La sal común es NaCl.',
    'magnesio'     => 'Arde con luz blanca intensísima (bengalas y flashes antiguos). El agua de mar es amarga por el cloruro de magnesio.',
    'aluminio'     => 'Hasta 1886 era más caro que el oro. Hoy es el metal más abundante de la corteza terrestre.',
    'silicio'      => 'Segundo elemento más abundante en la corteza (28%). Base de casi todos los chips y células solares.',
    'fosforo'      => 'El fósforo blanco se inflama solo en el aire y sigue ardiendo bajo el agua.',
    'azufre'       => 'El olor a huevos podridos es sulfuro de hidrógeno. Los volcanes expulsan muchísimo azufre.',
    'cloro'        => 'Gas verde tóxico usado en la Primera Guerra Mundial. El 99% del cloro de tu cuerpo está en la sal de mesa.',
    'argon'        => 'Tercer gas más abundante en la atmósfera (0,93%). Su nombre significa “perezoso” porque es totalmente inerte.',
    'potasio'      => 'Un plátano maduro tiene tanto K-40 radiactivo que puede activar un contador Geiger.',
    'calcio'       => 'Tus huesos y dientes son básicamente fosfato de calcio. La caliza y el mármol son carbonato de calcio.',
    'escandio'     => 'Usado en aleaciones ultraligeras de bicicletas de alta gama y bates de béisbol.',
    'titanio'      => 'Tan fuerte como el acero pero 45% más ligero. El cuerpo humano lo tolera perfectamente (implantes).',
    'vanadio'      => 'El acero con vanadio es el de las herramientas que casi no se rompen.',
    'cromo'        => 'Da el brillo inoxidable al acero y el color verde a las esmeraldas.',
    'manganeso'    => 'Imprescindible para la fotosíntesis. El fondo oceánico está cubierto de nódulos ricos en manganeso.',
    'hierro'       => 'El núcleo de la Tierra es principalmente hierro. La hemoglobina lleva oxígeno gracias al hierro.',
    'cobalto'      => 'El Co-60 se usa en radioterapia contra el cáncer y da el azul intenso al vidrio.',
    'niquel'       => 'Las monedas de 5 céntimos son 75% cobre + 25% níquel. Muchas alergias a joyería son por níquel.',
    'cobre'        => 'Único metal coloreado (además del oro). Mata bacterias al contacto (manillas de hospital de cobre).',
    'cinc'         => 'Protege el hierro del óxido (galvanizado). El bronce es cobre + zinc.',
    'galio'        => 'Se derrite en la mano (29,8 °C) y vuelve quebradizo al aluminio al tocarlo.',
    'germanio'     => 'Predicho por Mendeleiev como “eka-silicio”. Los primeros transistores eran de germanio.',
    'arsenico'     => 'Veneno clásico, pero el arseniuro de galio (GaAs) se usa en LEDs y láseres.',
    'selenio'      => 'Las primeras fotocopiadoras y células solares usaban selenio. Calentado huele a rábano picante.',
    'bromo'        => 'Único no-metal líquido a temperatura ambiente (además del mercurio). Huele horrible y tiñe la piel de naranja.',
    'kripton'      => 'Significa “el oculto”. De aquí viene el nombre de la kriptonita de Superman.',
    'rubidio'      => 'El Rb-87 se usa para datar rocas de miles de millones de años. Relojes atómicos ultra-precisos.',
    'estroncio'    => 'El Sr-90 es un peligroso residuo nuclear. Da el rojo intenso a los fuegos artificiales.',
    'itrio'        => 'Fundamental en granates YAG para láseres y en superconductores de alta temperatura.',
    'circonio'     => 'Químicamente idéntico al hafnio (siempre juntos). Usado en reactores nucleares porque no absorbe neutrones.',
    'niobio'       => 'Imanes superconductores del LHC del CERN llevan niobio. Antes se llamaba columbio.',
    'molibdeno'    => 'La enzima que fija el nitrógeno en las plantas contiene molibdeno.',
    'tecnecio'     => 'Primer elemento producido artificialmente (1937). El Tc-99m se usa en el 80% de pruebas de medicina nuclear.',
    'rutenio'      => 'Las puntas de plumas estilográficas de lujo suelen ser de rutenio.',
    'rodio'        => 'El metal más caro del mundo. Usado en convertidores catalíticos y joyería blanca.',
    'paladio'      => 'Absorbe 900 veces su volumen en hidrógeno. Principal metal de los catalizadores de coches.',
    'plata'        => 'Mejor conductor eléctrico y térmico. Las nanopartículas de plata matan bacterias (calcetines antiolor).',
    'cadmio'       => 'Daba el amarillo intenso a los pigmentos de Van Gogh. Baterías Ni-Cd.',
    'indio'        => 'El óxido de indio-estaño (ITO) es la capa conductora transparente de las pantallas táctiles.',
    'estaño'       => 'Cuando se dobla una barra de estaño puro se oye el “grito del estaño”.',
    'antimonio'    => 'Aleado con plomo hace las balas más duras. Se usa contra la leishmaniasis.',
    'telurio'      => 'Incluso en cantidades mínimas huele horriblemente a ajo.',
    'yodo'         => 'Sublima a vapor violeta. Esencial para la tiroides; su carencia produce bocio.',
    'xenon'        => 'Único gas noble que forma compuestos estables conocidos. Se ha usado como anestésico.',
    'cesio'        => 'El Cs-133 define el segundo oficial. El cesio fundido es el mejor conductor eléctrico entre metales.',
    'bario'        => 'El sulfato de bario (papilla blanca) se bebe para rayos X del intestino. Fuegos artificiales verdes.',
    'lantano'      => 'Abre la serie de los lantánidos. Usado en lentes ópticas de alta calidad.',
    'cerio'        => 'El óxido de cerio es el mejor pulidor de cristales. Piedras de mechero son aleación Ce-Fe.',
    'praseodimio'  => 'Junto con neodimio forma los imanes más potentes del mundo (NdFeB).',
    'neodimio'     => 'Los imanes de neodimio pueden levantar miles de veces su propio peso.',
    'prometio'     => 'Todos sus isótopos son radiactivos. Se usó en baterías nucleares diminutas para marcapasos.',
    'samario'      => 'Imanes SmCo resisten hasta 350 °C.',
    'europio'      => 'Da el color rojo fosforescente de los viejos televisores y de los billetes de euro (antifalsificación).',
    'gadolinio'    => 'El mejor agente de contraste para resonancias magnéticas.',
    'terbio'       => 'Brilla verde fosforescente. Usado en pantallas trichromáticas antiguas.',
    'disprosio'    => 'Imprescindible en imanes de motores eléctricos de vehículos híbridos y eléctricos.',
    'holmio'       => 'Tiene el momento magnético más alto de todos los elementos.',
    'erbio'        => 'La fibra óptica dopada con erbio amplifica las señales de internet submarinas.',
    'tulio'        => 'El lantánido estable más raro. Se usa en detección antifraude de billetes.',
    'iterbio'      => 'Relojes atómicos de iterbio son 100 veces más precisos que los de cesio.',
    'lutecio'      => 'El Lu-177 se usa en terapias dirigidas contra cáncer de próstata avanzado.',
    'hafnio'       => 'Usado como dieléctrico en los chips más avanzados (Intel 7 nm y menores).',
    'tantalio'      => 'Tan biocompatible que se usa en implantes y condensadores de móviles.',
    'wolframio'    => 'Punto de fusión más alto de todos los metales (3422 °C). Filamento de las bombillas antiguas.',
    'renio'        => 'El metal más raro de la corteza. Las turbinas de aviones modernos pueden llevar hasta 70% de renio.',
    'osmio'        => 'El elemento más denso conocido (22,59 g/cm³). Su tetroxido huele fatal y es muy tóxico.',
    'iridio'       => 'La capa rica en iridio en todo el planeta marca la extinción de los dinosaurios (asteroide).',
    'platino'      => 'No se oxida nunca. Catalizador en coches y en quimioterapia (cisplatino).',
    'oro'          => 'Se puede laminar hasta ser transparente. Es el metal más maleable y dúctil.',
    'mercurio'     => 'Único metal líquido a temperatura ambiente. 13,6 veces más denso que el agua.',
    'talio'        => 'Veneno “perfecto” clásico porque es insípido e indetectable en autopsias antiguas.',
    'plomo'        => 'Los romanos se envenenaron lentamente con tuberías y vino endulzado con acetato de plomo.',
    'bismuto'      => 'Forma cristales iridiscentes espectaculares. Es el diamagnético más fuerte.',
    'polonio'      => 'Descubierto por Marie Curie. El Po-210 es millones de veces más tóxico que el cianuro.',
    'astato'       => 'El elemento natural más raro: hay menos de 30 gramos en toda la corteza terrestre.',
    'radon'        => 'Gas noble radiactivo. Segunda causa de cáncer de pulmón después del tabaco.',
    'francio'      => 'El elemento natural más inestable después del ástato. Vida media de 22 minutos.',
    'radio'        => 'Brilla en la oscuridad. Las trabajadoras que pintaban relojes con radio morían de cáncer.',
    'actinio'      => 'Abre la serie de los actínidos. Todos sus isótopos son radiactivos.',
    'torio'        => 'Se usa en mantos de lámparas de gas y podría ser combustible nuclear del futuro.',
    'protactinio'  => 'Tan raro y radiactivo que solo se han aislado unos pocos gramos en la historia.',
    'uranio'       => 'El uranio empobrecido es tan denso que perfora blindajes. Combustible de reactores nucleares.',
    'neptunio'     => 'Primer actínido transuránico. Se forma el Np-237 en reactores.',
    'plutonio'     => 'El Pu-238 alimenta las sondas Voyager desde hace casi 50 años (generadores termoeléctricos).',
    'americio'     => 'El Am-241 está en prácticamente todos los detectores de humo domésticos.',
    'curio'        => 'Brilla en la oscuridad por su propia radiactividad. Nombrado en honor a los Curie.',
    'berkelio'     => 'Nombrado por la ciudad de Berkeley. Solo se han producido unos pocos gramos en totales.',
    'californio'   => 'El Cf-252 se usa en detectores de explosivos y tratamientos contra cáncer.',
    'einstenio'    => 'Nombrado por Albert Einstein. Solo se han producido cantidades microscópicas.',
    'fermio'       => 'Nombrado por Enrico Fermi. Detectado por primera vez en los restos de la primera bomba H.',
    'mendelevio'   => 'Nombrado por Dmitri Mendeleiev. Solo se han hecho unos pocos átomos.',
    'nobelio'      => 'Nombrado por Alfred Nobel. Vida media de minutos.',
    'lawrencio'    => 'Último actínido. Nombrado por Ernest Lawrence (inventor del ciclotrón).',
    'rutherfordio' => 'Primer elemento transférrrico. Sintetizado en 1964-1969.',
    'dubnio'       => 'Larga disputa de nombres entre EE.UU. y Rusia. Antes se llamó hahnio.',
    'seaborgio'    => 'Nombrado por Glenn T. Seaborg (único vivo en recibir ese honor).',
    'bohrio'       => 'Nombrado por Niels Bohr.',
    'hassio'       => 'Nombrado por el estado alemán de Hesse (donde está el GSI).',
    'meitnerio'    => 'Nombrado por Lise Meitner, codescubridora de la fisión nuclear.',
    'darmstadio'  => 'Sintetizado en Darmstadt, Alemania.',
    'roentgenio'   => 'Nombrado por Wilhelm Röntgen (descubridor de los rayos X).',
    'copernicio'   => 'Nombrado por Nicolás Copérnico. Se cree que podría ser líquido a temperatura ambiente.',
    'nihonio'      => 'Primer elemento nombrado por un país asiático (Japón, “Nihon”).',
    'flerovio'     => 'Nombrado por el laboratorio Flerov en Rusia.',
    'moscovio'     => 'Nombrado por la región de Moscú.',
    'livermorio'   => 'Nombrado por el Lawrence Livermore National Laboratory (EE.UU.).',
    // CORRECCIÓN respecto del original: en datos.py esta clave decía 'teneso',
    // pero en la tabla el elemento se llama 'tennessinio'. Como las claves no
    // coincidían, este dato curioso era imposible de mostrar: el programa
    // buscaba 'tennessinio' y nunca lo encontraba. Es un error clásico y muy
    // difícil de ver, porque no rompe nada: simplemente no pasa nada.
    'tennessinio'  => 'Nombrado por Tennessee (donde está el Oak Ridge National Laboratory).',
    'oganeson'     => '',
];

return $datosCuriosos;
