<?php
/**
 * =============================================================================
 *  tabla_periodica.php  —  LOS DATOS DE LOS 118 ELEMENTOS
 * =============================================================================
 *
 *  EN PYTHON esto era un diccionario:
 *
 *      elementos = {
 *          "hidrogeno": {
 *              "Nombre": "Hidrógeno",
 *              "NumeroAtomico": 1,
 *              ...
 *          },
 *      }
 *
 *  EN PHP no existen los "diccionarios": existe UN SOLO tipo llamado ARRAY
 *  que sirve tanto de lista como de diccionario. Se escribe con corchetes
 *  y se usa la flecha  =>  en lugar de los dos puntos  :
 *
 *      $elementos = [
 *          'hidrogeno' => [
 *              'Nombre' => 'Hidrógeno',
 *              'NumeroAtomico' => 1,
 *              ...
 *          ],
 *      ];
 *
 *  Otras dos diferencias que se ven en este archivo:
 *
 *   1) Las variables en PHP SIEMPRE empiezan con  $  (dólar).
 *   2) Cada instrucción termina en  ;  (punto y coma).
 *
 *  Al final del archivo hacemos  return $elementos;  Eso permite que otro
 *  archivo escriba:
 *
 *      $elementos = require 'includes/tabla_periodica.php';
 *
 *  y reciba el array completo. Es el equivalente PHP del
 *  "from tabla_periodica import elementos" de Python.
 * =============================================================================
 */

$elementos = [
    'hidrogeno' => [
        'Nombre' => 'Hidrógeno',
        'NumeroAtomico' => 1,
        'Simbolo' => 'H',
        'MasaAtomica' => 1.008,
        'Grupo' => 1,
        'Periodo' => 1,
        'Bloque' => 's',
        'Radiactivo' => false,
    ],
    'helio' => [
        'Nombre' => 'Helio',
        'NumeroAtomico' => 2,
        'Simbolo' => 'He',
        'MasaAtomica' => 4.0026,
        'Grupo' => 18,
        'Periodo' => 1,
        'Bloque' => 'p',
        'Radiactivo' => false,
    ],
    'litio' => [
        'Nombre' => 'Litio',
        'NumeroAtomico' => 3,
        'Simbolo' => 'Li',
        'MasaAtomica' => 6.94,
        'Grupo' => 1,
        'Periodo' => 2,
        'Bloque' => 's',
        'Radiactivo' => false,
    ],
    'berilio' => [
        'Nombre' => 'Berilio',
        'NumeroAtomico' => 4,
        'Simbolo' => 'Be',
        'MasaAtomica' => 9.0122,
        'Grupo' => 2,
        'Periodo' => 2,
        'Bloque' => 's',
        'Radiactivo' => false,
    ],
    'boro' => [
        'Nombre' => 'Boro',
        'NumeroAtomico' => 5,
        'Simbolo' => 'B',
        'MasaAtomica' => 10.81,
        'Grupo' => 13,
        'Periodo' => 2,
        'Bloque' => 'p',
        'Radiactivo' => false,
    ],
    'carbono' => [
        'Nombre' => 'Carbono',
        'NumeroAtomico' => 6,
        'Simbolo' => 'C',
        'MasaAtomica' => 12.011,
        'Grupo' => 14,
        'Periodo' => 2,
        'Bloque' => 'p',
        'Radiactivo' => false,
    ],
    'nitrogeno' => [
        'Nombre' => 'Nitrógeno',
        'NumeroAtomico' => 7,
        'Simbolo' => 'N',
        'MasaAtomica' => 14.007,
        'Grupo' => 15,
        'Periodo' => 2,
        'Bloque' => 'p',
        'Radiactivo' => false,
    ],
    'oxigeno' => [
        'Nombre' => 'Oxígeno',
        'NumeroAtomico' => 8,
        'Simbolo' => 'O',
        'MasaAtomica' => 15.999,
        'Grupo' => 16,
        'Periodo' => 2,
        'Bloque' => 'p',
        'Radiactivo' => false,
    ],
    'fluor' => [
        'Nombre' => 'Flúor',
        'NumeroAtomico' => 9,
        'Simbolo' => 'F',
        'MasaAtomica' => 18.998,
        'Grupo' => 17,
        'Periodo' => 2,
        'Bloque' => 'p',
        'Radiactivo' => false,
    ],
    'neon' => [
        'Nombre' => 'Neón',
        'NumeroAtomico' => 10,
        'Simbolo' => 'Ne',
        'MasaAtomica' => 20.18,
        'Grupo' => 18,
        'Periodo' => 2,
        'Bloque' => 'p',
        'Radiactivo' => false,
    ],
    'sodio' => [
        'Nombre' => 'Sodio',
        'NumeroAtomico' => 11,
        'Simbolo' => 'Na',
        'MasaAtomica' => 22.99,
        'Grupo' => 1,
        'Periodo' => 3,
        'Bloque' => 's',
        'Radiactivo' => false,
    ],
    'magnesio' => [
        'Nombre' => 'Magnesio',
        'NumeroAtomico' => 12,
        'Simbolo' => 'Mg',
        'MasaAtomica' => 24.305,
        'Grupo' => 2,
        'Periodo' => 3,
        'Bloque' => 's',
        'Radiactivo' => false,
    ],
    'aluminio' => [
        'Nombre' => 'Aluminio',
        'NumeroAtomico' => 13,
        'Simbolo' => 'Al',
        'MasaAtomica' => 26.982,
        'Grupo' => 13,
        'Periodo' => 3,
        'Bloque' => 'p',
        'Radiactivo' => false,
    ],
    'silicio' => [
        'Nombre' => 'Silicio',
        'NumeroAtomico' => 14,
        'Simbolo' => 'Si',
        'MasaAtomica' => 28.085,
        'Grupo' => 14,
        'Periodo' => 3,
        'Bloque' => 'p',
        'Radiactivo' => false,
    ],
    'fosforo' => [
        'Nombre' => 'Fósforo',
        'NumeroAtomico' => 15,
        'Simbolo' => 'P',
        'MasaAtomica' => 30.974,
        'Grupo' => 15,
        'Periodo' => 3,
        'Bloque' => 'p',
        'Radiactivo' => false,
    ],
    'azufre' => [
        'Nombre' => 'Azufre',
        'NumeroAtomico' => 16,
        'Simbolo' => 'S',
        'MasaAtomica' => 32.06,
        'Grupo' => 16,
        'Periodo' => 3,
        'Bloque' => 'p',
        'Radiactivo' => false,
    ],
    'cloro' => [
        'Nombre' => 'Cloro',
        'NumeroAtomico' => 17,
        'Simbolo' => 'Cl',
        'MasaAtomica' => 35.45,
        'Grupo' => 17,
        'Periodo' => 3,
        'Bloque' => 'p',
        'Radiactivo' => false,
    ],
    'argon' => [
        'Nombre' => 'Argón',
        'NumeroAtomico' => 18,
        'Simbolo' => 'Ar',
        'MasaAtomica' => 39.948,
        'Grupo' => 18,
        'Periodo' => 3,
        'Bloque' => 'p',
        'Radiactivo' => false,
    ],
    'potasio' => [
        'Nombre' => 'Potasio',
        'NumeroAtomico' => 19,
        'Simbolo' => 'K',
        'MasaAtomica' => 39.098,
        'Grupo' => 1,
        'Periodo' => 4,
        'Bloque' => 's',
        'Radiactivo' => false,
    ],
    'calcio' => [
        'Nombre' => 'Calcio',
        'NumeroAtomico' => 20,
        'Simbolo' => 'Ca',
        'MasaAtomica' => 40.078,
        'Grupo' => 2,
        'Periodo' => 4,
        'Bloque' => 's',
        'Radiactivo' => false,
    ],
    'escandio' => [
        'Nombre' => 'Escandio',
        'NumeroAtomico' => 21,
        'Simbolo' => 'Sc',
        'MasaAtomica' => 44.956,
        'Grupo' => 3,
        'Periodo' => 4,
        'Bloque' => 'd',
        'Radiactivo' => false,
    ],
    'titanio' => [
        'Nombre' => 'Titanio',
        'NumeroAtomico' => 22,
        'Simbolo' => 'Ti',
        'MasaAtomica' => 47.867,
        'Grupo' => 4,
        'Periodo' => 4,
        'Bloque' => 'd',
        'Radiactivo' => false,
    ],
    'vanadio' => [
        'Nombre' => 'Vanadio',
        'NumeroAtomico' => 23,
        'Simbolo' => 'V',
        'MasaAtomica' => 50.942,
        'Grupo' => 5,
        'Periodo' => 4,
        'Bloque' => 'd',
        'Radiactivo' => false,
    ],
    'cromo' => [
        'Nombre' => 'Cromo',
        'NumeroAtomico' => 24,
        'Simbolo' => 'Cr',
        'MasaAtomica' => 51.996,
        'Grupo' => 6,
        'Periodo' => 4,
        'Bloque' => 'd',
        'Radiactivo' => false,
    ],
    'manganeso' => [
        'Nombre' => 'Manganeso',
        'NumeroAtomico' => 25,
        'Simbolo' => 'Mn',
        'MasaAtomica' => 54.938,
        'Grupo' => 7,
        'Periodo' => 4,
        'Bloque' => 'd',
        'Radiactivo' => false,
    ],
    'hierro' => [
        'Nombre' => 'Hierro',
        'NumeroAtomico' => 26,
        'Simbolo' => 'Fe',
        'MasaAtomica' => 55.845,
        'Grupo' => 8,
        'Periodo' => 4,
        'Bloque' => 'd',
        'Radiactivo' => false,
    ],
    'cobalto' => [
        'Nombre' => 'Cobalto',
        'NumeroAtomico' => 27,
        'Simbolo' => 'Co',
        'MasaAtomica' => 58.933,
        'Grupo' => 9,
        'Periodo' => 4,
        'Bloque' => 'd',
        'Radiactivo' => false,
    ],
    'niquel' => [
        'Nombre' => 'Níquel',
        'NumeroAtomico' => 28,
        'Simbolo' => 'Ni',
        'MasaAtomica' => 58.693,
        'Grupo' => 10,
        'Periodo' => 4,
        'Bloque' => 'd',
        'Radiactivo' => false,
    ],
    'cobre' => [
        'Nombre' => 'Cobre',
        'NumeroAtomico' => 29,
        'Simbolo' => 'Cu',
        'MasaAtomica' => 63.546,
        'Grupo' => 11,
        'Periodo' => 4,
        'Bloque' => 'd',
        'Radiactivo' => false,
    ],
    'cinc' => [
        'Nombre' => 'Cinc',
        'NumeroAtomico' => 30,
        'Simbolo' => 'Zn',
        'MasaAtomica' => 65.38,
        'Grupo' => 12,
        'Periodo' => 4,
        'Bloque' => 'd',
        'Radiactivo' => false,
    ],
    'galio' => [
        'Nombre' => 'Galio',
        'NumeroAtomico' => 31,
        'Simbolo' => 'Ga',
        'MasaAtomica' => 69.723,
        'Grupo' => 13,
        'Periodo' => 4,
        'Bloque' => 'p',
        'Radiactivo' => false,
    ],
    'germanio' => [
        'Nombre' => 'Germanio',
        'NumeroAtomico' => 32,
        'Simbolo' => 'Ge',
        'MasaAtomica' => 72.63,
        'Grupo' => 14,
        'Periodo' => 4,
        'Bloque' => 'p',
        'Radiactivo' => false,
    ],
    'arsenico' => [
        'Nombre' => 'Arsénico',
        'NumeroAtomico' => 33,
        'Simbolo' => 'As',
        'MasaAtomica' => 74.922,
        'Grupo' => 15,
        'Periodo' => 4,
        'Bloque' => 'p',
        'Radiactivo' => false,
    ],
    'selenio' => [
        'Nombre' => 'Selenio',
        'NumeroAtomico' => 34,
        'Simbolo' => 'Se',
        'MasaAtomica' => 78.971,
        'Grupo' => 16,
        'Periodo' => 4,
        'Bloque' => 'p',
        'Radiactivo' => false,
    ],
    'bromo' => [
        'Nombre' => 'Bromo',
        'NumeroAtomico' => 35,
        'Simbolo' => 'Br',
        'MasaAtomica' => 79.904,
        'Grupo' => 17,
        'Periodo' => 4,
        'Bloque' => 'p',
        'Radiactivo' => false,
    ],
    'kripton' => [
        'Nombre' => 'Kriptón',
        'NumeroAtomico' => 36,
        'Simbolo' => 'Kr',
        'MasaAtomica' => 83.798,
        'Grupo' => 18,
        'Periodo' => 4,
        'Bloque' => 'p',
        'Radiactivo' => false,
    ],
    'rubidio' => [
        'Nombre' => 'Rubidio',
        'NumeroAtomico' => 37,
        'Simbolo' => 'Rb',
        'MasaAtomica' => 85.468,
        'Grupo' => 1,
        'Periodo' => 5,
        'Bloque' => 's',
        'Radiactivo' => false,
    ],
    'estroncio' => [
        'Nombre' => 'Estroncio',
        'NumeroAtomico' => 38,
        'Simbolo' => 'Sr',
        'MasaAtomica' => 87.62,
        'Grupo' => 2,
        'Periodo' => 5,
        'Bloque' => 's',
        'Radiactivo' => false,
    ],
    'itrio' => [
        'Nombre' => 'Itrio',
        'NumeroAtomico' => 39,
        'Simbolo' => 'Y',
        'MasaAtomica' => 88.906,
        'Grupo' => 3,
        'Periodo' => 5,
        'Bloque' => 'd',
        'Radiactivo' => false,
    ],
    'circonio' => [
        'Nombre' => 'Circonio',
        'NumeroAtomico' => 40,
        'Simbolo' => 'Zr',
        'MasaAtomica' => 91.224,
        'Grupo' => 4,
        'Periodo' => 5,
        'Bloque' => 'd',
        'Radiactivo' => false,
    ],
    'niobio' => [
        'Nombre' => 'Niobio',
        'NumeroAtomico' => 41,
        'Simbolo' => 'Nb',
        'MasaAtomica' => 92.906,
        'Grupo' => 5,
        'Periodo' => 5,
        'Bloque' => 'd',
        'Radiactivo' => false,
    ],
    'molibdeno' => [
        'Nombre' => 'Molibdeno',
        'NumeroAtomico' => 42,
        'Simbolo' => 'Mo',
        'MasaAtomica' => 95.95,
        'Grupo' => 6,
        'Periodo' => 5,
        'Bloque' => 'd',
        'Radiactivo' => false,
    ],
    'tecnecio' => [
        'Nombre' => 'Tecnecio',
        'NumeroAtomico' => 43,
        'Simbolo' => 'Tc',
        'MasaAtomica' => 98,
        'Grupo' => 7,
        'Periodo' => 5,
        'Bloque' => 'd',
        'Radiactivo' => true,
    ],
    'rutenio' => [
        'Nombre' => 'Rutenio',
        'NumeroAtomico' => 44,
        'Simbolo' => 'Ru',
        'MasaAtomica' => 101.07,
        'Grupo' => 8,
        'Periodo' => 5,
        'Bloque' => 'd',
        'Radiactivo' => false,
    ],
    'rodio' => [
        'Nombre' => 'Rodio',
        'NumeroAtomico' => 45,
        'Simbolo' => 'Rh',
        'MasaAtomica' => 102.91,
        'Grupo' => 9,
        'Periodo' => 5,
        'Bloque' => 'd',
        'Radiactivo' => false,
    ],
    'paladio' => [
        'Nombre' => 'Paladio',
        'NumeroAtomico' => 46,
        'Simbolo' => 'Pd',
        'MasaAtomica' => 106.42,
        'Grupo' => 10,
        'Periodo' => 5,
        'Bloque' => 'd',
        'Radiactivo' => false,
    ],
    'plata' => [
        'Nombre' => 'Plata',
        'NumeroAtomico' => 47,
        'Simbolo' => 'Ag',
        'MasaAtomica' => 107.87,
        'Grupo' => 11,
        'Periodo' => 5,
        'Bloque' => 'd',
        'Radiactivo' => false,
    ],
    'cadmio' => [
        'Nombre' => 'Cadmio',
        'NumeroAtomico' => 48,
        'Simbolo' => 'Cd',
        'MasaAtomica' => 112.41,
        'Grupo' => 12,
        'Periodo' => 5,
        'Bloque' => 'd',
        'Radiactivo' => false,
    ],
    'indio' => [
        'Nombre' => 'Indio',
        'NumeroAtomico' => 49,
        'Simbolo' => 'In',
        'MasaAtomica' => 114.82,
        'Grupo' => 13,
        'Periodo' => 5,
        'Bloque' => 'p',
        'Radiactivo' => false,
    ],
    'estaño' => [
        'Nombre' => 'Estaño',
        'NumeroAtomico' => 50,
        'Simbolo' => 'Sn',
        'MasaAtomica' => 118.71,
        'Grupo' => 14,
        'Periodo' => 5,
        'Bloque' => 'p',
        'Radiactivo' => false,
    ],
    'antimonio' => [
        'Nombre' => 'Antimonio',
        'NumeroAtomico' => 51,
        'Simbolo' => 'Sb',
        'MasaAtomica' => 121.76,
        'Grupo' => 15,
        'Periodo' => 5,
        'Bloque' => 'p',
        'Radiactivo' => false,
    ],
    'telurio' => [
        'Nombre' => 'Telurio',
        'NumeroAtomico' => 52,
        'Simbolo' => 'Te',
        'MasaAtomica' => 127.6,
        'Grupo' => 16,
        'Periodo' => 5,
        'Bloque' => 'p',
        'Radiactivo' => false,
    ],
    'yodo' => [
        'Nombre' => 'Yodo',
        'NumeroAtomico' => 53,
        'Simbolo' => 'I',
        'MasaAtomica' => 126.9,
        'Grupo' => 17,
        'Periodo' => 5,
        'Bloque' => 'p',
        'Radiactivo' => false,
    ],
    'xenon' => [
        'Nombre' => 'Xenón',
        'NumeroAtomico' => 54,
        'Simbolo' => 'Xe',
        'MasaAtomica' => 131.29,
        'Grupo' => 18,
        'Periodo' => 5,
        'Bloque' => 'p',
        'Radiactivo' => false,
    ],
    'cesio' => [
        'Nombre' => 'Cesio',
        'NumeroAtomico' => 55,
        'Simbolo' => 'Cs',
        'MasaAtomica' => 132.91,
        'Grupo' => 1,
        'Periodo' => 6,
        'Bloque' => 's',
        'Radiactivo' => false,
    ],
    'bario' => [
        'Nombre' => 'Bario',
        'NumeroAtomico' => 56,
        'Simbolo' => 'Ba',
        'MasaAtomica' => 137.33,
        'Grupo' => 2,
        'Periodo' => 6,
        'Bloque' => 's',
        'Radiactivo' => false,
    ],
    'lantano' => [
        'Nombre' => 'Lantano',
        'NumeroAtomico' => 57,
        'Simbolo' => 'La',
        'MasaAtomica' => 138.91,
        'Grupo' => 'Lantánidos',
        'Periodo' => 6,
        'Bloque' => 'f',
        'Radiactivo' => false,
    ],
    'cerio' => [
        'Nombre' => 'Cerio',
        'NumeroAtomico' => 58,
        'Simbolo' => 'Ce',
        'MasaAtomica' => 140.12,
        'Grupo' => 'Lantánidos',
        'Periodo' => 6,
        'Bloque' => 'f',
        'Radiactivo' => false,
    ],
    'praseodimio' => [
        'Nombre' => 'Praseodimio',
        'NumeroAtomico' => 59,
        'Simbolo' => 'Pr',
        'MasaAtomica' => 140.91,
        'Grupo' => 'Lantánidos',
        'Periodo' => 6,
        'Bloque' => 'f',
        'Radiactivo' => false,
    ],
    'neodimio' => [
        'Nombre' => 'Neodimio',
        'NumeroAtomico' => 60,
        'Simbolo' => 'Nd',
        'MasaAtomica' => 144.24,
        'Grupo' => 'Lantánidos',
        'Periodo' => 6,
        'Bloque' => 'f',
        'Radiactivo' => false,
    ],
    'prometio' => [
        'Nombre' => 'Prometio',
        'NumeroAtomico' => 61,
        'Simbolo' => 'Pm',
        'MasaAtomica' => 145,
        'Grupo' => 'Lantánidos',
        'Periodo' => 6,
        'Bloque' => 'f',
        'Radiactivo' => true,
    ],
    'samario' => [
        'Nombre' => 'Samario',
        'NumeroAtomico' => 62,
        'Simbolo' => 'Sm',
        'MasaAtomica' => 150.36,
        'Grupo' => 'Lantánidos',
        'Periodo' => 6,
        'Bloque' => 'f',
        'Radiactivo' => false,
    ],
    'europio' => [
        'Nombre' => 'Europio',
        'NumeroAtomico' => 63,
        'Simbolo' => 'Eu',
        'MasaAtomica' => 151.96,
        'Grupo' => 'Lantánidos',
        'Periodo' => 6,
        'Bloque' => 'f',
        'Radiactivo' => false,
    ],
    'gadolinio' => [
        'Nombre' => 'Gadolinio',
        'NumeroAtomico' => 64,
        'Simbolo' => 'Gd',
        'MasaAtomica' => 157.25,
        'Grupo' => 'Lantánidos',
        'Periodo' => 6,
        'Bloque' => 'f',
        'Radiactivo' => false,
    ],
    'terbio' => [
        'Nombre' => 'Terbio',
        'NumeroAtomico' => 65,
        'Simbolo' => 'Tb',
        'MasaAtomica' => 158.93,
        'Grupo' => 'Lantánidos',
        'Periodo' => 6,
        'Bloque' => 'f',
        'Radiactivo' => false,
    ],
    'disprosio' => [
        'Nombre' => 'Disprosio',
        'NumeroAtomico' => 66,
        'Simbolo' => 'Dy',
        'MasaAtomica' => 162.5,
        'Grupo' => 'Lantánidos',
        'Periodo' => 6,
        'Bloque' => 'f',
        'Radiactivo' => false,
    ],
    'holmio' => [
        'Nombre' => 'Holmio',
        'NumeroAtomico' => 67,
        'Simbolo' => 'Ho',
        'MasaAtomica' => 164.93,
        'Grupo' => 'Lantánidos',
        'Periodo' => 6,
        'Bloque' => 'f',
        'Radiactivo' => false,
    ],
    'erbio' => [
        'Nombre' => 'Erbio',
        'NumeroAtomico' => 68,
        'Simbolo' => 'Er',
        'MasaAtomica' => 167.26,
        'Grupo' => 'Lantánidos',
        'Periodo' => 6,
        'Bloque' => 'f',
        'Radiactivo' => false,
    ],
    'tulio' => [
        'Nombre' => 'Tulio',
        'NumeroAtomico' => 69,
        'Simbolo' => 'Tm',
        'MasaAtomica' => 168.93,
        'Grupo' => 'Lantánidos',
        'Periodo' => 6,
        'Bloque' => 'f',
        'Radiactivo' => false,
    ],
    'iterbio' => [
        'Nombre' => 'Iterbio',
        'NumeroAtomico' => 70,
        'Simbolo' => 'Yb',
        'MasaAtomica' => 173.05,
        'Grupo' => 'Lantánidos',
        'Periodo' => 6,
        'Bloque' => 'f',
        'Radiactivo' => false,
    ],
    'lutecio' => [
        'Nombre' => 'Lutecio', // corregido: en el original decía "Luctecio"
        'NumeroAtomico' => 71,
        'Simbolo' => 'Lu',
        'MasaAtomica' => 174.97,
        'Grupo' => 3,
        'Periodo' => 6,
        'Bloque' => 'd',
        'Radiactivo' => false,
    ],
    'hafnio' => [
        'Nombre' => 'Hafnio',
        'NumeroAtomico' => 72,
        'Simbolo' => 'Hf',
        'MasaAtomica' => 178.49,
        'Grupo' => 4,
        'Periodo' => 6,
        'Bloque' => 'd',
        'Radiactivo' => false,
    ],
    'tantalio' => [
        'Nombre' => 'Tantalio',
        'NumeroAtomico' => 73,
        'Simbolo' => 'Ta',
        'MasaAtomica' => 180.95,
        'Grupo' => 5,
        'Periodo' => 6,
        'Bloque' => 'd',
        'Radiactivo' => false,
    ],
    'wolframio' => [
        'Nombre' => 'Wolframio',
        'NumeroAtomico' => 74,
        'Simbolo' => 'W',
        'MasaAtomica' => 183.84,
        'Grupo' => 6,
        'Periodo' => 6,
        'Bloque' => 'd',
        'Radiactivo' => false,
    ],
    'renio' => [
        'Nombre' => 'Renio',
        'NumeroAtomico' => 75,
        'Simbolo' => 'Re',
        'MasaAtomica' => 186.21,
        'Grupo' => 7,
        'Periodo' => 6,
        'Bloque' => 'd',
        'Radiactivo' => false,
    ],
    'osmio' => [
        'Nombre' => 'Osmio',
        'NumeroAtomico' => 76,
        'Simbolo' => 'Os',
        'MasaAtomica' => 190.23,
        'Grupo' => 8,
        'Periodo' => 6,
        'Bloque' => 'd',
        'Radiactivo' => false,
    ],
    'iridio' => [
        'Nombre' => 'Iridio',
        'NumeroAtomico' => 77,
        'Simbolo' => 'Ir',
        'MasaAtomica' => 192.22,
        'Grupo' => 9,
        'Periodo' => 6,
        'Bloque' => 'd',
        'Radiactivo' => false,
    ],
    'platino' => [
        'Nombre' => 'Platino',
        'NumeroAtomico' => 78,
        'Simbolo' => 'Pt',
        'MasaAtomica' => 195.08,
        'Grupo' => 10,
        'Periodo' => 6,
        'Bloque' => 'd',
        'Radiactivo' => false,
    ],
    'oro' => [
        'Nombre' => 'Oro',
        'NumeroAtomico' => 79,
        'Simbolo' => 'Au',
        'MasaAtomica' => 196.97,
        'Grupo' => 11,
        'Periodo' => 6,
        'Bloque' => 'd',
        'Radiactivo' => false,
    ],
    'mercurio' => [
        'Nombre' => 'Mercurio',
        'NumeroAtomico' => 80,
        'Simbolo' => 'Hg',
        'MasaAtomica' => 200.59,
        'Grupo' => 12,
        'Periodo' => 6,
        'Bloque' => 'd',
        'Radiactivo' => false,
    ],
    'talio' => [
        'Nombre' => 'Talio',
        'NumeroAtomico' => 81,
        'Simbolo' => 'Tl',
        'MasaAtomica' => 204.38,
        'Grupo' => 13,
        'Periodo' => 6,
        'Bloque' => 'p',
        'Radiactivo' => false,
    ],
    'plomo' => [
        'Nombre' => 'Plomo',
        'NumeroAtomico' => 82,
        'Simbolo' => 'Pb',
        'MasaAtomica' => 207.2,
        'Grupo' => 14,
        'Periodo' => 6,
        'Bloque' => 'p',
        'Radiactivo' => false,
    ],
    'bismuto' => [
        'Nombre' => 'Bismuto',
        'NumeroAtomico' => 83,
        'Simbolo' => 'Bi',
        'MasaAtomica' => 208.98,
        'Grupo' => 15,
        'Periodo' => 6,
        'Bloque' => 'p',
        'Radiactivo' => false,
    ],
    'polonio' => [
        'Nombre' => 'Polonio',
        'NumeroAtomico' => 84,
        'Simbolo' => 'Po',
        'MasaAtomica' => 209,
        'Grupo' => 16,
        'Periodo' => 6,
        'Bloque' => 'p',
        'Radiactivo' => true,
    ],
    'astato' => [
        'Nombre' => 'Astato',
        'NumeroAtomico' => 85,
        'Simbolo' => 'At',
        'MasaAtomica' => 210,
        'Grupo' => 17,
        'Periodo' => 6,
        'Bloque' => 'p',
        'Radiactivo' => true,
    ],
    'radon' => [
        'Nombre' => 'Radón',
        'NumeroAtomico' => 86,
        'Simbolo' => 'Rn',
        'MasaAtomica' => 222,
        'Grupo' => 18,
        'Periodo' => 6,
        'Bloque' => 'p',
        'Radiactivo' => true,
    ],
    'francio' => [
        'Nombre' => 'Francio',
        'NumeroAtomico' => 87,
        'Simbolo' => 'Fr',
        'MasaAtomica' => 223,
        'Grupo' => 1,
        'Periodo' => 7,
        'Bloque' => 's',
        'Radiactivo' => true,
    ],
    'radio' => [
        'Nombre' => 'Radio',
        'NumeroAtomico' => 88,
        'Simbolo' => 'Ra',
        'MasaAtomica' => 226,
        'Grupo' => 2,
        'Periodo' => 7,
        'Bloque' => 's',
        'Radiactivo' => true,
    ],
    'actinio' => [
        'Nombre' => 'Actinio',
        'NumeroAtomico' => 89,
        'Simbolo' => 'Ac',
        'MasaAtomica' => 227,
        'Grupo' => 'Actínidos',
        'Periodo' => 7,
        'Bloque' => 'f',
        'Radiactivo' => true,
    ],
    'torio' => [
        'Nombre' => 'Torio',
        'NumeroAtomico' => 90,
        'Simbolo' => 'Th',
        'MasaAtomica' => 232.04,
        'Grupo' => 'Actínidos',
        'Periodo' => 7,
        'Bloque' => 'f',
        'Radiactivo' => true,
    ],
    'protactinio' => [
        'Nombre' => 'Protactinio',
        'NumeroAtomico' => 91,
        'Simbolo' => 'Pa',
        'MasaAtomica' => 231.04,
        'Grupo' => 'Actínidos',
        'Periodo' => 7,
        'Bloque' => 'f',
        'Radiactivo' => true,
    ],
    'uranio' => [
        'Nombre' => 'Uranio',
        'NumeroAtomico' => 92,
        'Simbolo' => 'U',
        'MasaAtomica' => 238.03,
        'Grupo' => 'Actínidos',
        'Periodo' => 7,
        'Bloque' => 'f',
        'Radiactivo' => true,
    ],
    'neptunio' => [
        'Nombre' => 'Neptunio',
        'NumeroAtomico' => 93,
        'Simbolo' => 'Np',
        'MasaAtomica' => 237,
        'Grupo' => 'Actínidos',
        'Periodo' => 7,
        'Bloque' => 'f',
        'Radiactivo' => true,
    ],
    'plutonio' => [
        'Nombre' => 'Plutonio',
        'NumeroAtomico' => 94,
        'Simbolo' => 'Pu',
        'MasaAtomica' => 244,
        'Grupo' => 'Actínidos',
        'Periodo' => 7,
        'Bloque' => 'f',
        'Radiactivo' => true,
    ],
    'americio' => [
        'Nombre' => 'Americio',
        'NumeroAtomico' => 95,
        'Simbolo' => 'Am',
        'MasaAtomica' => 243,
        'Grupo' => 'Actínidos',
        'Periodo' => 7,
        'Bloque' => 'f',
        'Radiactivo' => true,
    ],
    'curio' => [
        'Nombre' => 'Curio',
        'NumeroAtomico' => 96,
        'Simbolo' => 'Cm',
        'MasaAtomica' => 247,
        'Grupo' => 'Actínidos',
        'Periodo' => 7,
        'Bloque' => 'f',
        'Radiactivo' => true,
    ],
    'berkelio' => [
        'Nombre' => 'Berkelio',
        'NumeroAtomico' => 97,
        'Simbolo' => 'Bk',
        'MasaAtomica' => 247,
        'Grupo' => 'Actínidos',
        'Periodo' => 7,
        'Bloque' => 'f',
        'Radiactivo' => true,
    ],
    'californio' => [
        'Nombre' => 'Californio',
        'NumeroAtomico' => 98,
        'Simbolo' => 'Cf',
        'MasaAtomica' => 251,
        'Grupo' => 'Actínidos',
        'Periodo' => 7,
        'Bloque' => 'f',
        'Radiactivo' => true,
    ],
    'einstenio' => [
        'Nombre' => 'Einstenio',
        'NumeroAtomico' => 99,
        'Simbolo' => 'Es',
        'MasaAtomica' => 252,
        'Grupo' => 'Actínidos',
        'Periodo' => 7,
        'Bloque' => 'f',
        'Radiactivo' => true,
    ],
    'fermio' => [
        'Nombre' => 'Fermio',
        'NumeroAtomico' => 100,
        'Simbolo' => 'Fm',
        'MasaAtomica' => 257,
        'Grupo' => 'Actínidos',
        'Periodo' => 7,
        'Bloque' => 'f',
        'Radiactivo' => true,
    ],
    'mendelevio' => [
        'Nombre' => 'Mendelevio',
        'NumeroAtomico' => 101,
        'Simbolo' => 'Md',
        'MasaAtomica' => 258,
        'Grupo' => 'Actínidos',
        'Periodo' => 7,
        'Bloque' => 'f',
        'Radiactivo' => true,
    ],
    'nobelio' => [
        'Nombre' => 'Nobelio',
        'NumeroAtomico' => 102,
        'Simbolo' => 'No',
        'MasaAtomica' => 259,
        'Grupo' => 'Actínidos',
        'Periodo' => 7,
        'Bloque' => 'f',
        'Radiactivo' => true,
    ],
    'lawrencio' => [
        'Nombre' => 'Lawrencio',
        'NumeroAtomico' => 103,
        'Simbolo' => 'Lr',
        'MasaAtomica' => 262,
        'Grupo' => 'Actínidos',
        'Periodo' => 7,
        'Bloque' => 'f',
        'Radiactivo' => true,
    ],
    'rutherfordio' => [
        'Nombre' => 'Rutherfordio',
        'NumeroAtomico' => 104,
        'Simbolo' => 'Rf',
        'MasaAtomica' => 267,
        'Grupo' => 4,
        'Periodo' => 7,
        'Bloque' => 'd',
        'Radiactivo' => true,
    ],
    'dubnio' => [
        'Nombre' => 'Dubnio',
        'NumeroAtomico' => 105,
        'Simbolo' => 'Db',
        'MasaAtomica' => 270,
        'Grupo' => 5,
        'Periodo' => 7,
        'Bloque' => 'd',
        'Radiactivo' => true,
    ],
    'seaborgio' => [
        'Nombre' => 'Seaborgio',
        'NumeroAtomico' => 106,
        'Simbolo' => 'Sg',
        'MasaAtomica' => 271,
        'Grupo' => 6,
        'Periodo' => 7,
        'Bloque' => 'd',
        'Radiactivo' => true,
    ],
    'bohrio' => [
        'Nombre' => 'Bohrio',
        'NumeroAtomico' => 107,
        'Simbolo' => 'Bh',
        'MasaAtomica' => 270,
        'Grupo' => 7,
        'Periodo' => 7,
        'Bloque' => 'd',
        'Radiactivo' => true,
    ],
    'hassio' => [
        'Nombre' => 'Hassio',
        'NumeroAtomico' => 108,
        'Simbolo' => 'Hs',
        'MasaAtomica' => 277,
        'Grupo' => 8,
        'Periodo' => 7,
        'Bloque' => 'd',
        'Radiactivo' => true,
    ],
    'meitnerio' => [
        'Nombre' => 'Meitnerio',
        'NumeroAtomico' => 109,
        'Simbolo' => 'Mt',
        'MasaAtomica' => 276,
        'Grupo' => 9,
        'Periodo' => 7,
        'Bloque' => 'd',
        'Radiactivo' => true,
    ],
    'darmstadio' => [
        'Nombre' => 'Darmstadio',
        'NumeroAtomico' => 110,
        'Simbolo' => 'Ds',
        'MasaAtomica' => 281,
        'Grupo' => 10,
        'Periodo' => 7,
        'Bloque' => 'd',
        'Radiactivo' => true,
    ],
    'roentgenio' => [
        'Nombre' => 'Roentgenio',
        'NumeroAtomico' => 111,
        'Simbolo' => 'Rg',
        'MasaAtomica' => 282,
        'Grupo' => 11,
        'Periodo' => 7,
        'Bloque' => 'd',
        'Radiactivo' => true,
    ],
    'copernicio' => [
        'Nombre' => 'Copernicio',
        'NumeroAtomico' => 112,
        'Simbolo' => 'Cn',
        'MasaAtomica' => 285,
        'Grupo' => 12,
        'Periodo' => 7,
        'Bloque' => 'd',
        'Radiactivo' => true,
    ],
    'nihonio' => [
        'Nombre' => 'Nihonio',
        'NumeroAtomico' => 113,
        'Simbolo' => 'Nh',
        'MasaAtomica' => 286,
        'Grupo' => 13,
        'Periodo' => 7,
        'Bloque' => 'p',
        'Radiactivo' => true,
    ],
    'flerovio' => [
        'Nombre' => 'Flerovio',
        'NumeroAtomico' => 114,
        'Simbolo' => 'Fl',
        'MasaAtomica' => 289,
        'Grupo' => 14,
        'Periodo' => 7,
        'Bloque' => 'p',
        'Radiactivo' => true,
    ],
    'moscovio' => [
        'Nombre' => 'Moscovio',
        'NumeroAtomico' => 115,
        'Simbolo' => 'Mc',
        'MasaAtomica' => 288,
        'Grupo' => 15,
        'Periodo' => 7,
        'Bloque' => 'p',
        'Radiactivo' => true,
    ],
    'livermorio' => [
        'Nombre' => 'Livermorio',
        'NumeroAtomico' => 116,
        'Simbolo' => 'Lv',
        'MasaAtomica' => 293,
        'Grupo' => 16,
        'Periodo' => 7,
        'Bloque' => 'p',
        'Radiactivo' => true,
    ],
    'tennessinio' => [
        'Nombre' => 'Tennessinio',
        'NumeroAtomico' => 117,
        'Simbolo' => 'Ts',
        'MasaAtomica' => 294,
        'Grupo' => 17,
        'Periodo' => 7,
        'Bloque' => 'p',
        'Radiactivo' => true,
    ],
    'oganeson' => [
        'Nombre' => 'Oganesón',
        'NumeroAtomico' => 118,
        'Simbolo' => 'Og',
        'MasaAtomica' => 294,
        'Grupo' => 18,
        'Periodo' => 7,
        'Bloque' => 'p',
        'Radiactivo' => true,
    ],
];

// Devolvemos el array a quien haya hecho el  require  de este archivo.
return $elementos;
